@startuml

package "GitHub account of document owner" {
    [Document repository\naka <b>upstream</b> repository] as Upstream
    [master branch] as Master

    Upstream - Master
}

package "Your GitHub account" {
    [Fork of document repository\naka <b>downstream</b> repository] as Downstream
    [master branch] as ContribMaster

    Downstream - ContribMaster
}

Upstream --> Downstream : (1) Fork

actor You

You -> ContribMaster : (2) Add/modify content

@enduml